try :
    print (x)
except :
    print ('error 404!')
    
#====================

try :
    print (x)
except Exception as e :
    print ('error 404!', e)
    
